---
version: 2.1
orbs:
  android: circleci/android@2.3.0
  slack: circleci/slack@4.12.5

project_directory: &project_directory ~/project

jobs:
  clean_build_test:
    working_directory: *project_directory
    docker:
      - image: cimg/android:2023.11
    steps:
      - checkout
      - attach_workspace:
          at: ~/project/
      - android/run-tests:
          working-directory: ~/project/
          test-command: ./gradlew test
      - run:
          name: Download Dependencies
          working_directory: ~/project/
          command: ./gradlew androidDependencies
      - run:
          name: Run Tests
          working_directory: ~/project/
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results

workflows:
  build:
    jobs:
      - clean_build_test
